FROM python:3.12.8-alpine

# Set working directory
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN apk add --no-cache python3-dev py3-pip && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# Expose port 8000 for the Django server
EXPOSE 8000

# Command to run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
